version: 2.1

jobs:
  build:
    macos:
      xcode: 15.0.1
    steps:
      - checkout
      - run:
          name: Install Fastlane
          command: gem install fastlane -NV
      - run:
          name: Run Tests
workflows:
  version: 2
  build:
    jobs:
      - build
