version: 2.1

jobs:
  build:
    macos:
      xcode: 15.0.1
    steps:
      - checkout
      - run:
          name: Install Fastlane
          command: gem install fastlane -NV
      - run:
          name: Remove corrupted Package.resolved
          command: rm /Users/distiller/project/GolfDeLaMarterie.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
      - run:
          name: Run Tests
          command: fastlane test
workflows:
  version: 2
  build:
    jobs:
      - build
