# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
lane :tests do
  run_tests(projet: "GolfDeLaMarterie.xcodeproj",
            device: "iPhone 15 Pro",
            scheme: "GolfDeLaMarterieTests")
    end
  end
